### ISSUE TITLE
"error_message" => "message is required"

### ISSUE THREAD

**Issue by Nes-cmd** [jaktechet/sms-ethiopia-developer-doc#2]
Even I have follwed this format, why It displays error message ""message is required" with status code of 400?

`$response = Http::withHeaders([
    'Content-Type' => 'application/json',
])->post('your_single_url', [
    'username' => 'your_username',
    'password' => 'your_password',
    'to' => '2519xxxxxxxxx',
    'message' => 'your_message',
]);`

**Comment by AdoniasCodes** [comment]
that error happened because you used "," at the end of the 'your message' section. Please remove that and it will work

**Comment by Nes-cmd** [comment]
The error was the API is expecting that the name of the message field as `text` not message, so your request should be like this `$response = Http::withHeaders([ 'Content-Type' => 'application/json', ])->post('your_single_url', [ 'username' => 'your_username', 'password' => 'your_password', 'to' => '2519xxxxxxxxx', 'text' => 'your_message', ]);` 

But the docomentation of laravel and some other language says as the field is message, so check both lol.
